enum PaymentTokenStatus {
  AVAILABLE = "AVAILABLE",
  CURRENTLY_IN_USE = "CURRENTLY_IN_USE",
  USED = "USED",
  EXPIRED = "EXPIRED",
  PREVERIFICATION = "PREVERIFICATION",
  VERIFYING = "VERIFYING",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
}

export default PaymentTokenStatus;
